// user
export const getAllUser = 'GET_ALL_USER_FULFILLED'
export const getAllUserPending = 'GET_ALL_USER_PENDING'
export const getAllUserError = 'GET_ALL_USER_REJECTED'
export const getDetailUser = 'GET_DETAIL_USER_FULFILLED'
export const getDetailUserPending = 'GET_DETAIL_USER_PENDING'
export const getDetailUserError = 'GET_DETAIL_USER_REJECTED'
export const getDetailByName = 'GET_DETAIL_BY_NAME_FULFILLED'
export const getDetailByNamePending = 'GET_DETAIL_BY_NAME_PENDING'
export const getDetailByNameError = 'GET_DETAIL_BY_NAME_REJECTED'
